### ISSUE TITLE
code release date

### ISSUE THREAD

**Issue by joemzhao** [uclanlp/ELMO-C#1]
dear authors,

thanks for the nice work and it's great to see the efficiency improvements! 

just wondering when would the implementation be available? that would be very helpful, thank you!

**Comment by liunian-harold-li** [comment]
Hi, thank you for your interest in our code. I am sorry that I forgot to monitor this repo and I did not see your question until today.

I am sorry for the delay and I am working to make the code available as soon as possible. The paper was finished a while ago so some additional work is needed before the release.

Thank you for your patience!

**Comment by joemzhao** [comment]
hi,

ok i see, and thanks a lot for the message!
